 --DROP DATABASE DBMATRICULA_CLASE


CREATE DATABASE DBMATRICULA_CLASE

GO

USE DBMATRICULA_CLASE

GO

--CREAR TABLA CARRERA
CREATE TABLE CARRERAS(
	COD_CARRERA VARCHAR(10) CONSTRAINT PK_CARRERAS PRIMARY KEY,
	NOMBRE_CARRERA VARCHAR(100) NOT NULL,
	TOTAL_CREDITOS INT NOT NULL,
	GRADO VARCHAR(14) NOT NULL DEFAULT 'BACHILLERATO'
)

-- RESTRICCIONES DE LA TABLA CARRERAS
ALTER TABLE CARRERAS ADD CONSTRAINT CHK_TCREDITOS 
CHECK(TOTAL_CREDITOS>0 AND TOTAL_CREDITOS<1000)

ALTER TABLE CARRERAS ADD CONSTRAINT CHK_GRADO 
CHECK(GRADO IN ('LICENCIATURA', 'BACHILLERATO','DIPLOMADO','MAESTRIA'))

--CREAR TABLA ESTUDIANTES
CREATE TABLE ESTUDIANTES(
	CARNET VARCHAR(6) CONSTRAINT PK_ESTUDIANTES PRIMARY KEY,
	ID_ESTUDIANTE VARCHAR(20) NOT NULL UNIQUE,
	NOMBRE_ESTUDIANTE VARCHAR(20) NOT NULL,
	PRIMER_APELLIDO_E VARCHAR(20) NOT NULL,
	SEGUNDO_APELLIDO_E VARCHAR(20),
	TELEFONO_ESTUDIANTE VARCHAR(8) NOT NULL,
	CORREO_ESTUDIANTE VARCHAR(25),
	FECHA_INGRESO DATE NOT NULL DEFAULT GETDATE(),
	ESTADO_ESTUDIANTE VARCHAR(3) NOT NULL DEFAULT 'ACT',
	BORRADO_E BIT NOT NULL DEFAULT 0
);

--RESTRICCIONES DE LA TABLA ESTUDIANTES
ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK_FECHAINGRESO 
CHECK(FECHA_INGRESO>=GETDATE())

ALTER TABLE ESTUDIANTES DROP CONSTRAINT CHK_FECHAINGRESO 

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CHK_ESTADOE 
CHECK(ESTADO_ESTUDIANTE in ('ACT','INA') 
and ESTADO_ESTUDIANTE = upper(ESTADO_ESTUDIANTE))

--CREAR LA TABLA PROFESORES
CREATE TABLE PROFESORES(
	COD_PROFESOR INT IDENTITY(1,1) CONSTRAINT PK_PROFESORES PRIMARY KEY,
	ID_PROFESOR VARCHAR(15) NOT NULL UNIQUE,
	NOMBRE_PROFESOR VARCHAR(25) NOT NULL,
	PRIMER_APELLIDO_P VARCHAR(20) NOT NULL,
	SEGUNDO_APELLIDO_P VARCHAR(20),
	TELEFONO_PROFESOR VARCHAR(8) NOT NULL,
	CORREO_PROFESOR VARCHAR(25),
	BORRADO_P BIT NOT NULL DEFAULT 0
)

--CREAR LA TABLA MATERIAS
CREATE TABLE MATERIAS(
	COD_MATERIA VARCHAR(10) CONSTRAINT PK_MATERIAS PRIMARY KEY,
	NOMBRE_MATERIA VARCHAR(120) NOT NULL,
	CREDITOS TINYINT NOT NULL,
	BORRADO_M BIT NOT NULL DEFAULT 0
)
--RESTRICCIONES DE LA TABLA MATERIA
ALTER TABLE MATERIAS ADD CONSTRAINT CHK_CREDITOS 
CHECK(CREDITOS BETWEEN 0 AND 12)


-- CREAR TABLA MATERIAS CARRERAS
CREATE TABLE MATERIAS_CARRERAS(
	COD_MATERIA_CARRERA INT IDENTITY(1,1) CONSTRAINT PK_MATERIAS_CARRERAS PRIMARY KEY,
	COD_CARRERA VARCHAR(10) NOT NULL,
	COD_MATERIA VARCHAR(10) NOT NULL,
	REQUISITO VARCHAR(10),
	COREQUISITO VARCHAR(10),
	BORRADO_MC BIT NOT NULL DEFAULT 0
)


-- CREAR TABLA MATERIAS_ABIERTAS

CREATE TABLE MATERIAS_ABIERTAS(
	COD_MATERIA_ABIERTA INT IDENTITY(1,1) CONSTRAINT PK_MATERIAS_ABIERTAS PRIMARY KEY,
	COD_MATERIA_CARRERA INT NOT NULL,
	COD_PROFESOR INT,
	GRUPO TINYINT,
	CUPO TINYINT default 30,
	COSTO DECIMAL(10,2),
	PERIODO TINYINT,
	ANIO SMALLINT,
	MAXIMO_DESCUENTO DECIMAL(4,2)
);

-- RESTRICCIONES DE LA TABLA MATERIAS_ABIERTAS
ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT CHK_COSTO CHECK(COSTO>0)

ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT CHK_MDESC 
CHECK(MAXIMO_DESCUENTO>=0 AND MAXIMO_DESCUENTO<100)


-- CREAR LA TABLA HORARIOS
CREATE TABLE HORARIOS(
	COD_MATERIA_ABIERTA INT,
	DIA CHAR(1) NOT NULL,
	HORA_INICIO TIME,
	HORA_FIN TIME
	CONSTRAINT PK_HORARIOS PRIMARY KEY(COD_MATERIA_ABIERTA,DIA,HORA_INICIO,HORA_FIN)
)

--RESTRICCIONES DE LA TABLA HORARIOS
ALTER TABLE HORARIOS ADD CONSTRAINT CHK_DIA
 CHECK(DIA IN('L','K','M','J','V','S') and DIA = upper(DIA))


-- CREAR LA TABLA MATRICULAS
CREATE TABLE MATRICULAS(
	NUM_RECIBO INT IDENTITY(1,1) CONSTRAINT PK_MATRICULAS PRIMARY KEY,
	CARNET VARCHAR(6) NOT NULL, FK
	FECHA DATETIME NOT NULL DEFAULT GETDATE(),
	MONTO DECIMAL(10,2) NOT NULL,
	DESCUENTO DECIMAL(10,2),
	ESTADO_M VARCHAR(3) NOT NULL DEFAULT 'ACT',
	USUARIO_MATRICULA VARCHAR(25) NOT NULL,
	OBSERVACIONES VARCHAR(250) 
)

-- RESTRICCIONES DE LA TABLA MATRICULAS
ALTER TABLE MATRICULAS ADD CONSTRAINT CHK_MONTOM CHECK(MONTO>=0)

ALTER TABLE MATRICULAS ADD CONSTRAINT CHK_DESCUENTOM CHECK(DESCUENTO>=0)

ALTER TABLE MATRICULAS ADD CONSTRAINT CHK_ESTADOM 
CHECK(ESTADO_M='ACT' OR ESTADO_M='INA')


-- CREAR LA TABLA DETALLE_MATRICULAS
CREATE TABLE DETALLE_MATRICULAS(
	NUM_RECIBO INT NOT NULL,
	COD_MATERIA_ABIERTA INT NOT NULL,
	PORCENTAJE_DESCUENTO DECIMAL(4,2) DEFAULT 0,
	NOTA_FINAL DECIMAL(5,2) DEFAULT 0,
	ESTADO_D VARCHAR(3) NOT NULL DEFAULT 'ACT'
	CONSTRAINT PK_DETALLE_MATRICULAS PRIMARY KEY(NUM_RECIBO,COD_MATERIA_ABIERTA)
)

-- RESTRICCIONES DE LA TABLA DETALLE_MATRICULAS
ALTER TABLE DETALLE_MATRICULAS ADD CONSTRAINT CHK_PDESCUENTO 
CHECK(PORCENTAJE_DESCUENTO>=0 AND PORCENTAJE_DESCUENTO<100)
--ALTER TABLE DETALLE_MATRICULAS ADD CONSTRAINT CHK_NOTA 
--CHECK(NOTA_FINAL>=0 AND NOTA_FINAL<=100)
ALTER TABLE DETALLE_MATRICULAS ADD CONSTRAINT CHK_NOTA_FINAL 
CHECK (NOTA_FINAL is null or (NOTA_FINAL >= 0 AND NOTA_FINAL<=100))

ALTER TABLE DETALLE_MATRICULAS ADD CONSTRAINT CHK_ESTADOD 
CHECK(ESTADO_D IN('ACT','RET','APR','REP'))


--*******************************************************************
-- REFERENCIAS

ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT FK_MATERIAS_CARRERAS1 
FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA)

ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT FK_MATERIAS_CARRERAS2 
FOREIGN KEY (COD_MATERIA) REFERENCES MATERIAS(COD_MATERIA)

ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT FK_MATERIAS_CARRERAS3 
FOREIGN KEY (REQUISITO) REFERENCES MATERIAS(COD_MATERIA)

ALTER TABLE MATERIAS_CARRERAS ADD CONSTRAINT FK_MATERIAS_CARRERAS4 
FOREIGN KEY (COREQUISITO) REFERENCES MATERIAS(COD_MATERIA)


ALTER TABLE DETALLE_MATRICULAS ADD CONSTRAINT FK_DETALLE_MATRICULAS 
FOREIGN KEY (NUM_RECIBO) REFERENCES MATRICULAS(NUM_RECIBO)

ALTER TABLE DETALLE_MATRICULAS ADD CONSTRAINT FK_DETALLE_MATRICULAS1 
FOREIGN KEY (COD_MATERIA_ABIERTA) REFERENCES MATERIAS_ABIERTAS(COD_MATERIA_ABIERTA)

ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT FK_MATERIAS_ABIERTAS1 
FOREIGN KEY (COD_MATERIA_CARRERA) REFERENCES MATERIAS_CARRERAS(COD_MATERIA_CARRERA)

ALTER TABLE MATERIAS_ABIERTAS ADD CONSTRAINT FK_MATERIAS_ABIERTAS2 
FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESORES(COD_PROFESOR)

ALTER TABLE HORARIOS ADD CONSTRAINT FK_HORARIOS 
FOREIGN KEY (COD_MATERIA_ABIERTA) REFERENCES MATERIAS_ABIERTAS(COD_MATERIA_ABIERTA)

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULAS 
FOREIGN KEY (CARNET) REFERENCES ESTUDIANTES(CARNET)


