CREATE DATABASE EJEMPLO_CLASE1
GO

USE EJEMPLO_CLASE1
GO



CREATE TABLE TBL_CLIENTES(
ID_CLIENTES int PRIMARY KEY NOT NULL,
NOMBRE varchar(20) NOT NULL,
APELLIDO varchar(20) NOT NULL, 
DIRECCION_EXACTA varchar(150) NOT NULL,
PROVINCIA varchar(20) NOT NULL DEFAULT 'ALAJUELA',--CHECK
CANTON varchar(20) DEFAULT 'NARANJO', --VALOR DETERMINADO NARANJO 
FECHA varchar(20) NOT NULL,
CANTIDAD_IDIOMAS int NOT NULL -- VALOR DETERMINADO 1
);

--DETERMIANAR
ALTER TABLE TBL_CLIENTES
ADD DEFAULT getDate() FOR FECHA; -- VALOR DETERMINADO FECHA ACTUAL

ALTER TABLE  TBL_CLIENTES
ADD DEFAULT 1 FOR CANTIDAD_IDIOMAS; -- VALOR DETERMINADO 1

ALTER TABLE  TBL_CLIENTES
ADD CONSTRAINT CK_PROVINCIA CHECK(PROVINCIA IN ('ALAJUELA','SAN JOSE','PUNTARENAS',
'LIMON', 'GUANACASTE', 'CARTAGO', 'HEREDIA'))

CREATE TABLE INVENTARIO_PRODUCTOS(
ID_PRODUCTO int NOT NULL PRIMARY KEY,
NOMBRE_PRODUCTO varchar(30), 
DESCRIPCION varchar(100)
);

CREATE TABLE FACTURAS(
ID_FACTURA int PRIMARY KEY NOT NULL, 
ID_CLIENTE int NOT NULL,
FECHA datetime DEFAULT getdate() NOT NULL,
ID_PRODUCTO int NOT NULL,
CANTIDAD float NOT NULL DEFAULT 1 CHECK(CANTIDAD > 0)
);

ALTER TABLE TBL_CLIENTES
ADD FOREIGN KEY(ID_CLIENTE) REFERENCES FACTURAS(ID_CLIENTE);

ALTER TABLE FACTURAS
ADD FOREIGN KEY(ID_PRODUCTO) REFERENCES INVENTARIO_PRODUCTOS(PRODUCTO);

SELECT * FROM PROFESORES;
SELECT * FROM ESTUDIANTES;
