CREATE DATABASE VETERINARIA_MUNDO_MASCOTA
GO

USE VETERINARIA_MUNDO_MASCOTA
GO 

--crea la tabla planillas 
CREATE TABLE PLANILLAS(
ID_PLANILLA int PRIMARY KEY, -- PK 
ID_EMPLEADO varchar(20) NOT NULL, -- FK de la tabla EMPLEADO
FECHA datetime NOT NULL,
HORAS_NORMALES int NOT NULL,
HORAS_EXTRA int NOT NULL,
SALARIO int NOT NULL
);

CREATE TABLE EMPLEADOS (
ID_EMPLEADO varchar(20) PRIMARY KEY, -- PK, PERO FUE FK EN LA TABLA PLANILLAS
IDENTIFICACION varchar(20) NOT NULL,
NOMBRE varchar(20) NOT NULL,
APELLIDO1 varchar(20) NOT NULL,
APELLIDO2 varchar(20) NOT NULL,
TELEFONO int NOT NULL,
PUESTO varchar(20) NOT NULL,
HORARIO datetime NOT NULL,
EMAIL varchar(35) NOT NULL,
CUENTA_BANCARIA varchar(20) NOT NULL,
PAIS varchar(20) NOT NULL,
PROVINCIA varchar(20) NOT NULL, --AQUI NO ES DETERMINADO
DISTRITO varchar(20) NOT NULL,
FECHA_NACIMIENTO datetime NOT NULL,
ESTADO_CICIL varchar(20) NOT NULL
);


CREATE TABLE CITAS(
ID_CITAS int PRIMARY KEY,
ID_EMPLEADO varchar(20) NOT NULL,
ID_MASCOTA varchar(20) NOT NULL, 
FECHA date NOT  NULL,
HORA time NOT NULL
);

CREATE TABLE MASCOTAS (
ID_MASCOTA varchar(20) PRIMARY KEY,
ID_CLIENTE varchar(20) NOT NULL,
RAZA varchar(20) NOT NULL,
TAMANIO varchar(20) NOT NULL,
FECHA_NACIMIENTO datetime NOT NULL,
NOMBRE varchar(20) NOT NULL,
PESO int NOT NULL
);

CREATE TABLE CLIENTES (
ID_CLIENTE varchar(20) PRIMARY KEY, -- PK, PERO FUE FK EN LA TABLA PLANILLAS
IDENTIFICACION varchar(20) NOT NULL,
NOMBRE varchar(20) NOT NULL,
APELLIDO1 varchar(20) NOT NULL,
APELLIDO2 varchar(20) NOT NULL,
TELEFONO int NOT NULL,
EMAIL varchar(35) NOT NULL,
CUENTA_BANCARIA varchar(20) NOT NULL,
PAIS varchar(20) NOT NULL,
PROVINCIA varchar(20) NOT NULL, --AQUI NO ES DETERMINADO
DISTRITO varchar(20) NOT NULL,
FECHA_NACIMIENTO datetime NOT NULL,
ESTADO_CICIL varchar(20) NOT NULL
);

-- CREAR LAS LLAVES FORANEA 

ALTER TABLE PLANILLAS ADD CONSTRAINT FK_PLANILLAS_EMPLEADOS --ID_EMPLEADO QUE ESTA EN LA TABLA PLANILLA COMO LLAVE FORANEA 
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO); --ID_EMPLEADO ES LLAVE PRIMARIA EN EMPLEADOS

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_CLIENTES -- ID_CLIENTE FK EN MASCOTAS
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE); --ID_CLIENTE PK EN CLIENTES

ALTER TABLE CITAS ADD CONSTRAINT FK_CITAS_EMPLEADOS -- ID_EMPLEADO FK EN CITAS
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO); --ID_EMPLEADO PK EN EMPLEADOS

ALTER TABLE CITAS ADD CONSTRAINT FK_CITAS_MASCOTAS --ID_MASCOTAS FK EN CITAS 
FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA); --ID_MASCOTAS ES PK EN MASCOTAS


