CREATE DATABASE MI_PRIMERA_BD;
GO 

USE MI_PRIMERA_BD;
GO

CREATE TABLE CLIENTES(
ID_CLIENTE varchar(15),
NOMBRE varchar(25),
APELLIDO varchar(25),
DIRECCION_EXACTA varchar(150),
PROVINCIA varchar(15) DEFAULT 'ALAJUELA',
CANTON varchar(25),
FECHA_REGISTRO datetime,
CANTIDAD_IDIOMAS int
);

ALTER TABLE CLIENTES
ADD DEFAULT 'PALMARES' FOR CANTON;

ALTER TABLE CLIENTES
ADD DEFAULT getDate() FOR FECHA_REGISTRO;

ALTER TABLE CLIENTES
ADD DEFAULT 1 FOR CANTIDAD_IDIOMAS;


CREATE TABLE VACACIONES (
ID_VACACIONES int IDENTITY, --PRIMARY KEY,
FECHA_INICIO datetime,
FECHA_FINAL datetime,
OBVSERVACIONES varchar(250)
);

ALTER TABLE VACACIONES 
ADD CONSTRAINT PK_VACACIONES PRIMARY KEY (ID_VACACIONES);

CREATE TABLE CLIENTES2(
ID_CLIENTE2 int PRIMARY KEY IDENTITY,
NOMBRE2 varchar(30) UNIQUE NOT NULL,
APELLIDO varchar(30)
);

ALTER TABLE CLIENTES2
ALTER COLUMN NOMBRE2 varchar(20) NOT NULL;

CREATE TABLE ESTUDIANTES(
ID_ESTUDIANTE int NOT NULL,
CARNET int UNIQUE,
NOMBRE varchar(20),
APELLIDO varchar(20)
);

DROP TABLE ESTUDIANTES

ALTER TABLE ESTUDIANTES
ADD CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (ID_ESTUDIANTE);

ALTER TABLE ESTUDIANTES
ADD CONSTRAINT UQ_NOMBRE UNIQUE (NOMBRE);

CREATE TABLE ESTUDIANTES2(
ID_ESTUDIANTE2 int CHECK (ID_ESTUDIANTE2 > 0),
NOMBRE varchar(20),
APELLIDO varchar(20),
ESTADO varchar(3) CHECK (ESTADO = 'APR' OR ESTADO = 'REP' OR ESTADO = 'APL')
);


CREATE TABLE ESTUDIANTES3(
ID_ESTUDIANTE3 int PRIMARY KEY IDENTITY(1,1),
NOMBRE varchar(30),
APELLIDO varchar(20),
EDAD INT
);

ALTER TABLE ESTUDIANTES3 
ADD CONSTRAINT CK_EDAD CHECK(EDAD >= 18 AND EDAD <=80); 

CREATE TABLE ESTUDIANTES4(
ID_ESTUDIANTE int  IDENTITY CHECK (ID_ESTUDIANTE > 0) NOT NULL,
NOMBRE varchar(30),
APELLIDO varchar(20),
CONSTRAINT PK_ESTUDIANTE4 PRIMARY KEY (ID_ESTUDUANTE),
);


CREATE TABLE DETALLE_MATRICULA (
ID_MATRICULA int IDENTITY(1,1),
ID_MATERIA_ABIERTA int NOT NULL,
PORCENTAJE_DESCUENTO decimal(4,2) NOT NULL,
ESTADO varchar(3) NOT NULL,
NOTA_FINAL DECIMAL(5,2) NULL,
OBVSERVACIONES varchar(400) NULL,
CONSTRAINT PK_DETALLES_MATRICULA PRIMARY KEY(ID_MATRICULA, ID_MATERIA_ABIERTA)
);

CREATE TABLE INVENTARIO_PRODUCTOS(
ID_PRODUCTO int  PRIMARY KEY NOT NULL,
NOMBRE_PRODUCTO varchar(20),
DESCRIPCION varchar(500)
);

CREATE TABLE FACTURAS (
ID_FACTURA int CONSTRAINT PK_FACTURAS PRIMARY KEY,
FECHA datetime,
ID_PRODUCTO int CONSTRAINT FK_INVENTARIO_PRODUCTOS FOREIGN KEY REFERENCES 
INVENTARIO_PRODUCTOS (ID_PRODUCTO)
);

CREATE TABLE FACTURAS1(
ID_FACTURA int,
FECHA datetime,
ID_PRODUCTO int,
CANTIDAD float,
CONSTRAINT PK_FACTURAS1 PRIMARY KEY (ID_FACTURA),
CONSTRAINT FK_INVENTARIO_P FOREIGN KEY (ID_PRODUCTO)
 REFERENCES INVENTARIO_PRODUCTOS(ID_PRODUCTO)

);

CREATE TABLE FACTURAS2(
ID_FACTURA int CONSTRAINT PK_FACTURAS PRIMARY KEY IDENTITY,
FECHA datetime, 
ID_PROD int,
CANTIDAD float,

);

ALTER TABLE FACTURAS2 
ADD CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY(ID_PROD)
REFERENCES INVENTARIO_PRODUCTOS(ID_PRODUCTO);

