--Ejercicio compartido en clase 
--1
CREATE DATABASE DIAGNOSTICO;
GO

USE DIAGNOSTICO;
GO

--2
CREATE TABLE CLIENTES(
NOMBRE varchar(20),APELLIDO varchar(20),PROVINCIA varchar(10), CANTON varchar(25),
);


--3
ALTER TABLE CLIENTES ADD ID_CLIENTE int; 

--SELECT NOMBRE, PROVINCIA, ID_CLIENTE FROM CLIENTES ; --PARA OBVSERVAR el nuevo campo

--4
ALTER TABLE CLIENTES ALTER COLUMN ID_CLIENTE int NOT NULL; -- HAY QUE PONER NOT NULL

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY(ID_CLIENTE);

--5
ALTER TABLE CLIENTES 
ADD CONSTRAINT CK_PROVINCIA CHECK (PROVINCIA IN ('ALAJUELA' , 
	'SAN JOSE','HEREDIA','CARTAGO','LIMON','GUANACASTE','PUNTARENAS'));

	/*ALTER TABLE CLIENTES
ADD CONSTRAINT CK_PROVINCIA CHECK (PROVINCIA='ALAJUELA' or PROVINCIA='SAN JOSE' or PROVINCIA='HEREDIA' 
   or PROVINCIA='CARTAGO' or PROVINCIA='LIMON' or PROVINCIA='GUANACASTE' or PROVINCIA='PUNTARENAS');
*/


--6 
ALTER TABLE CLIENTES ADD TELEF varchar(9) NOT NULL;

--CAMBIAR NOMBRE RECORDAR QUE PARA BORRARLO HAY QUE ELIMINAR LA TABLA O COLUMNA 
--SE PUEDE HACER CON EL SIGUIENTE PROCEDIMIENTO ALMACENADO

GO 
EXEC sp_rename 'CLIENTES.TELEF' , 'TELEFONO_CLIENTE';
GO 

--7

CREATE TABLE MASCOTAS (
	ID_MASCOTA int CONSTRAINT PK_MASCOTAS PRIMARY KEY IDENTITY (100,1), --INICIA EN 100, INCREMENTOS EN 1
	NOMBRE_MASCOTA varchar(25),
	TIPO_ANIMAL varchar(25),
	RAZA varchar(35)
);

--8 AGREGAR NUEVO CAMPO 'PESO' SOLO CON ADD
ALTER TABLE MASCOTAS ADD PESO float NOT NULL;

 --RESTRICCION PARA QUE NO ADMITA VALORES MAYORES A 9 
ALTER TABLE MASCOTAS 
	ADD CONSTRAINT CK_PESO CHECK ( PESO > 0);


--9 Cree una relación entre las tablas MASCOTAS y CLIENTES.
--EN TABLA MASCONTAS NO ESTA ID_CLIENTES HAY QUE AGREGARLO PARA LUEGO HACER LA RELACION 
ALTER TABLE MASCOTAS 
	ADD ID_CLIENTE int NOT NULL;

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_CLIENTES --ID_CLIENTES ES LLAVE FORANEA EN LA TABLA MASCOTAS
	FOREIGN KEY (ID_CLIENTE)  REFERENCES CLIENTES(ID_CLIENTE); -- ID_CLIENTES ES LLAVE PRIMARIA EN LA TABLA CLIENTES


--10 Crear tabla vacunas
CREATE TABLE VACUNAS (
	ID_VACUNA int CONSTRAINT PK_VACUNAS PRIMARY KEY IDENTITY(1,1), --SE PUEDE OMITIR EL (1,1) YA QUE ES EL VALOR PREDETERMINADO PERTENECE A LA TABLA
	ID_MASCOTA int,
	FECHA datetime
);


--11 LLAVE FORANEA ID MASCOTAS 
ALTER TABLE VACUNAS ADD CONSTRAINT FK_VACUNAS_MASCOTAS
	FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA)
	ON DELETE NO ACTION --SE HACE EN LLAVES FORANEAS, CUANDO SE BORRE LA PK MASCOTAS, SI ESTA RELACIONADO CON OTRAS TRABLAS, O NO BORRAR O BORRAR EN CASCADA 
	ON UPDATE NO ACTION;

--12 Definir la fecha actual como valor por defecto para el campo FECHA.

ALTER TABLE VACUNAS 
	ADD CONSTRAINT DF_FECHA DEFAULT getDate() FOR FECHA; --FECHA PERTENECE A LA TAB;A 







